"""Remove tags table

Revision ID: 0760ed2b9287
Revises: 1f3fc50f8ae1
Create Date: 2025-10-19 18:31:38.120804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0760ed2b9287'
down_revision: Union[str, Sequence[str], None] = '1f3fc50f8ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Try to drop tags table if it exists
    try:
        op.drop_table('tags')
    except:
        pass
    
    # Try to drop indexes if they exist
    try:
        op.drop_index(op.f('idx_reviewer_status'), table_name='reviewer_applications')
    except:
        pass
    try:
        op.drop_index(op.f('idx_reviewer_user_id'), table_name='reviewer_applications')
    except:
        pass
    try:
        op.drop_index(op.f('idx_submissions_category'), table_name='submissions')
    except:
        pass
    try:
        op.drop_index(op.f('idx_submissions_handled_by'), table_name='submissions')
    except:
        pass
    try:
        op.drop_index(op.f('idx_submissions_status'), table_name='submissions')
    except:
        pass
    try:
        op.drop_index(op.f('idx_submissions_timestamp'), table_name='submissions')
    except:
        pass
    try:
        op.drop_index(op.f('idx_submissions_user_id'), table_name='submissions')
    except:
        pass
    try:
        op.drop_index(op.f('idx_user_states_timestamp'), table_name='user_states')
    except:
        pass
    try:
        op.drop_index(op.f('idx_users_last_interaction'), table_name='users')
    except:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Try to create tags table if it doesn't exist
    try:
        op.create_table('tags',
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('usage_count', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('name')
        )
    except:
        pass
    
    # Recreate indexes
    try:
        op.create_index(op.f('idx_users_last_interaction'), 'users', ['last_interaction'], unique=False)
    except:
        pass
    try:
        op.create_index(op.f('idx_user_states_timestamp'), 'user_states', ['timestamp'], unique=False)
    except:
        pass
    try:
        op.create_index(op.f('idx_submissions_user_id'), 'submissions', ['user_id'], unique=False)
    except:
        pass
    try:
        op.create_index(op.f('idx_submissions_timestamp'), 'submissions', ['timestamp'], unique=False)
    except:
        pass
    try:
        op.create_index(op.f('idx_submissions_status'), 'submissions', ['status'], unique=False)
    except:
        pass
    try:
        op.create_index(op.f('idx_submissions_handled_by'), 'submissions', ['handled_by'], unique=False)
    except:
        pass
    try:
        op.create_index(op.f('idx_submissions_category'), 'submissions', ['category'], unique=False)
    except:
        pass
    try:
        op.create_index(op.f('idx_reviewer_user_id'), 'reviewer_applications', ['user_id'], unique=False)
    except:
        pass
    try:
        op.create_index(op.f('idx_reviewer_status'), 'reviewer_applications', ['status'], unique=False)
    except:
        pass
    # ### end Alembic commands ###