"""Add permissions column to reviewer_applications table

Revision ID: 1f3fc50f8ae1
Revises: 
Create Date: 2025-10-19 00:29:59.536740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f3fc50f8ae1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviewer_applications', sa.Column('permissions', sa.Text(), nullable=True))
    op.drop_index(op.f('idx_reviewer_status'), table_name='reviewer_applications')
    op.drop_index(op.f('idx_reviewer_user_id'), table_name='reviewer_applications')
    op.drop_index(op.f('idx_submissions_category'), table_name='submissions')
    op.drop_index(op.f('idx_submissions_handled_by'), table_name='submissions')
    op.drop_index(op.f('idx_submissions_status'), table_name='submissions')
    op.drop_index(op.f('idx_submissions_timestamp'), table_name='submissions')
    op.drop_index(op.f('idx_submissions_user_id'), table_name='submissions')
    op.drop_index(op.f('idx_user_states_timestamp'), table_name='user_states')
    op.drop_index(op.f('idx_users_last_interaction'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_last_interaction'), 'users', ['last_interaction'], unique=False)
    op.create_index(op.f('idx_user_states_timestamp'), 'user_states', ['timestamp'], unique=False)
    op.create_index(op.f('idx_submissions_user_id'), 'submissions', ['user_id'], unique=False)
    op.create_index(op.f('idx_submissions_timestamp'), 'submissions', ['timestamp'], unique=False)
    op.create_index(op.f('idx_submissions_status'), 'submissions', ['status'], unique=False)
    op.create_index(op.f('idx_submissions_handled_by'), 'submissions', ['handled_by'], unique=False)
    op.create_index(op.f('idx_submissions_category'), 'submissions', ['category'], unique=False)
    op.create_index(op.f('idx_reviewer_user_id'), 'reviewer_applications', ['user_id'], unique=False)
    op.create_index(op.f('idx_reviewer_status'), 'reviewer_applications', ['status'], unique=False)
    op.drop_column('reviewer_applications', 'permissions')
    # ### end Alembic commands ###
