"""remove tags table

Revision ID: 605b4103db85
Revises: 0760ed2b9287
Create Date: 2025-10-20 19:38:16.884265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '605b4103db85'
down_revision: Union[str, Sequence[str], None] = '0760ed2b9287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Try to drop tags table if it exists
    try:
        op.drop_table('tags')
    except:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Try to create tags table if it doesn't exist
    try:
        op.create_table('tags',
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('usage_count', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('name')
        )
    except:
        pass
    # ### end Alembic commands ###